version: 2.1
jobs:
  build_deploy:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: building the app
          command: cd / && npm install && npm run build
      - run:
          name: syncing the files with S3
          command: aws s3 sync ./app/build s3://ci-cd-example

workflows:
  execute_bulk:
    jobs:
      - build_deploy